{ dmenu, i3status }:

''
  # This file has been auto-generated by i3-config-wizard(1).
  # It will not be overwritten, so edit it as you like.
  #
  # Should you change your keyboard layout some time, delete
  # this file and re-run i3-config-wizard(1).
  #
  ...
''
